services:
  web:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    command: php artisan queue:work
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    scale: 2

  scheduler:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    command: php artisan schedule:work
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
