services:
  app:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
